openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /users:
    get:
      tags:
        - chatterbook-controller
      operationId: list_of_users
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /users/{name}:
    get:
      tags:
        - chatterbook-controller
      operationId: getUserByN
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
  /users/posts/{name}:
    get:
      tags:
        - chatterbook-controller
      operationId: getChatterPostsPerUser
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChatterPost'
  /users/index/{indx}:
    get:
      tags:
        - chatterbook-controller
      operationId: getUserByIndx
      parameters:
        - name: indx
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
  /hi:
    get:
      tags:
        - chatterbook-controller
      operationId: hello
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    ChatterPost:
      type: object
      properties:
        text:
          type: string
    User:
      type: object
      properties:
        name:
          type: string
        chatterPosts:
          type: array
          items:
            $ref: '#/components/schemas/ChatterPost'
